---
openapi: 3.0.2
info:
  title: soap-document-upload
  version: 1.0.0
  description: Specification for a SOAP-based document upload service
paths:
  /upload:
    post:
      requestBody:
        content:
          text/xml: {}
        required: true
components:
  responses:
    soap-response:
      content:
        text/xml: {}
      description: ""
